---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: drupal
  namespace: flux-system
spec:
  chart:
    spec:
      chart: template-controller
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: kluctl
  interval: 10m0s
  releaseName: template-controller
  targetNamespace: kluctl-system

