FROM bitnami/drupal:10

# To-do: Composer cache dir. Consider composer-no-cache option.
# See https://github.com/composer/composer/issues/10906
USER root
ENV COMPOSER_CACHE_READ_ONLY=1
RUN mkdir /.composer \
    && chmod a+w /.composer
USER 1001

# Add our files in place necessary for composer install
# We must remove the Bitnami composer.lock file so ours doesn't conflict
RUN rm /opt/bitnami/drupal/composer.lock
COPY app/composer.json /opt/bitnami/drupal/composer.json
RUN cd /opt/bitnami/drupal && composer install

ENTRYPOINT [ "/opt/bitnami/scripts/drupal/entrypoint.sh" ]
CMD [ "/opt/bitnami/scripts/apache/run.sh" ]
